CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_BLINK_SLEEP_250MS=y
CONFIG_ADVANCED_LED_SETTINGS=y
CONFIG_ENABLE_LED_DEBUGGING=n
CONFIG_CUSTOM_BLINK_PATTERN=n
CONFIG_LED_BRIGHTNESS=80
CONFIG_LED_FADE_DURATION_MS=250